<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PuNeEtDocASAP" name="executeMain.ExecuteSuit" tests="8" failures="1" timestamp="8 Jan 2016 07:07:52 GMT" time="48.147" errors="1">
  <testcase name="loginCredentialsReadXl" time="0.000" classname="executeMain.ExecuteSuit"/>
  <testcase name="adminLogin" time="4.399" classname="executeMain.ExecuteSuit"/>
  <testcase name="alert" time="3.290" classname="executeMain.ExecuteSuit"/>
  <testcase name="fetchValuesFromPendingUserTab" time="0.437" classname="executeMain.ExecuteSuit"/>
  <testcase name="loginPage" time="13.398" classname="executeMain.ExecuteSuit">
    <error type="java.lang.AssertionError" message="expected [LogIn] but found [Log In]">
      <![CDATA[java.lang.AssertionError: expected [LogIn] but found [Log In]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at executeMain.ExecuteSuit.loginPage(ExecuteSuit.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- loginPage -->
  <testcase name="providerAccountLogin" time="8.785" classname="executeMain.ExecuteSuit"/>
  <testcase name="frameHandle" time="0.855" classname="executeMain.ExecuteSuit"/>
  <testcase name="adminAccount" time="16.983" classname="executeMain.ExecuteSuit"/>
</testsuite> <!-- executeMain.ExecuteSuit -->
